language: node_js
node_js:
  - 0.6
before_script:
  - export PHAROS_AUTH_STRATEGY=callback
  - export PHAROS_BASE_URL=http://localhost:3000/
  - export PHAROS_CALLBACK=http://dl.dropbox.com/u/16019885/auth
  - export PHAROS_PASSWORD=test
  - export PHAROS_REDIS_URL=redis://localhost:6379/ 